<div class="page-title">
    <h1><?php echo Mage::helper('currencyconverter')->__('Currency Converter') ?></h1>
</div>

<?php
/** @var $this SQLI_CurrencyConverter_Block_List */
?>

<table class="cc-list">
    <tr>
        <th>Currency From</th>
        <th>Currency To</th>
        <th>Amount to convert</th>
        <th>Rate of conversion</th>
        <th>Result of conversion</th>
    </tr>
    <?php echo $this->listOfConversion(); ?>
</table>